// flow-typed signature: 3029a15437279d5115b9dcb4da43a3fa
// flow-typed version: <<STUB>>/socket.io-client_v4.5.1/flow_v0.182.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'socket.io-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'socket.io-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'socket.io-client/build/cjs/browser-entrypoint' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/cjs/contrib/backo2' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/cjs' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/cjs/manager' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/cjs/on' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/cjs/socket' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/cjs/url' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/esm-debug/browser-entrypoint' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/esm-debug/contrib/backo2' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/esm-debug' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/esm-debug/manager' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/esm-debug/on' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/esm-debug/socket' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/esm-debug/url' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/esm/browser-entrypoint' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/esm/contrib/backo2' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/esm' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/esm/manager' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/esm/on' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/esm/socket' {
  declare module.exports: any;
}

declare module 'socket.io-client/build/esm/url' {
  declare module.exports: any;
}

declare module 'socket.io-client/dist/socket.io.esm.min' {
  declare module.exports: any;
}

declare module 'socket.io-client/dist/socket.io' {
  declare module.exports: any;
}

declare module 'socket.io-client/dist/socket.io.min' {
  declare module.exports: any;
}

declare module 'socket.io-client/dist/socket.io.msgpack.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'socket.io-client/build/cjs/browser-entrypoint.js' {
  declare module.exports: $Exports<'socket.io-client/build/cjs/browser-entrypoint'>;
}
declare module 'socket.io-client/build/cjs/contrib/backo2.js' {
  declare module.exports: $Exports<'socket.io-client/build/cjs/contrib/backo2'>;
}
declare module 'socket.io-client/build/cjs/index' {
  declare module.exports: $Exports<'socket.io-client/build/cjs'>;
}
declare module 'socket.io-client/build/cjs/index.js' {
  declare module.exports: $Exports<'socket.io-client/build/cjs'>;
}
declare module 'socket.io-client/build/cjs/manager.js' {
  declare module.exports: $Exports<'socket.io-client/build/cjs/manager'>;
}
declare module 'socket.io-client/build/cjs/on.js' {
  declare module.exports: $Exports<'socket.io-client/build/cjs/on'>;
}
declare module 'socket.io-client/build/cjs/socket.js' {
  declare module.exports: $Exports<'socket.io-client/build/cjs/socket'>;
}
declare module 'socket.io-client/build/cjs/url.js' {
  declare module.exports: $Exports<'socket.io-client/build/cjs/url'>;
}
declare module 'socket.io-client/build/esm-debug/browser-entrypoint.js' {
  declare module.exports: $Exports<'socket.io-client/build/esm-debug/browser-entrypoint'>;
}
declare module 'socket.io-client/build/esm-debug/contrib/backo2.js' {
  declare module.exports: $Exports<'socket.io-client/build/esm-debug/contrib/backo2'>;
}
declare module 'socket.io-client/build/esm-debug/index' {
  declare module.exports: $Exports<'socket.io-client/build/esm-debug'>;
}
declare module 'socket.io-client/build/esm-debug/index.js' {
  declare module.exports: $Exports<'socket.io-client/build/esm-debug'>;
}
declare module 'socket.io-client/build/esm-debug/manager.js' {
  declare module.exports: $Exports<'socket.io-client/build/esm-debug/manager'>;
}
declare module 'socket.io-client/build/esm-debug/on.js' {
  declare module.exports: $Exports<'socket.io-client/build/esm-debug/on'>;
}
declare module 'socket.io-client/build/esm-debug/socket.js' {
  declare module.exports: $Exports<'socket.io-client/build/esm-debug/socket'>;
}
declare module 'socket.io-client/build/esm-debug/url.js' {
  declare module.exports: $Exports<'socket.io-client/build/esm-debug/url'>;
}
declare module 'socket.io-client/build/esm/browser-entrypoint.js' {
  declare module.exports: $Exports<'socket.io-client/build/esm/browser-entrypoint'>;
}
declare module 'socket.io-client/build/esm/contrib/backo2.js' {
  declare module.exports: $Exports<'socket.io-client/build/esm/contrib/backo2'>;
}
declare module 'socket.io-client/build/esm/index' {
  declare module.exports: $Exports<'socket.io-client/build/esm'>;
}
declare module 'socket.io-client/build/esm/index.js' {
  declare module.exports: $Exports<'socket.io-client/build/esm'>;
}
declare module 'socket.io-client/build/esm/manager.js' {
  declare module.exports: $Exports<'socket.io-client/build/esm/manager'>;
}
declare module 'socket.io-client/build/esm/on.js' {
  declare module.exports: $Exports<'socket.io-client/build/esm/on'>;
}
declare module 'socket.io-client/build/esm/socket.js' {
  declare module.exports: $Exports<'socket.io-client/build/esm/socket'>;
}
declare module 'socket.io-client/build/esm/url.js' {
  declare module.exports: $Exports<'socket.io-client/build/esm/url'>;
}
declare module 'socket.io-client/dist/socket.io.esm.min.js' {
  declare module.exports: $Exports<'socket.io-client/dist/socket.io.esm.min'>;
}
declare module 'socket.io-client/dist/socket.io.js' {
  declare module.exports: $Exports<'socket.io-client/dist/socket.io'>;
}
declare module 'socket.io-client/dist/socket.io.min.js' {
  declare module.exports: $Exports<'socket.io-client/dist/socket.io.min'>;
}
declare module 'socket.io-client/dist/socket.io.msgpack.min.js' {
  declare module.exports: $Exports<'socket.io-client/dist/socket.io.msgpack.min'>;
}
